# Generated by Django 5.2.6 on 2025-09-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableNumber', models.CharField(max_length=20, verbose_name='Номер стола')),
                ('Information', models.CharField(max_length=250, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
            },
        ),
    ]
