# Generated by Django 5.2.6 on 2025-09-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Workplace',
        ),
    ]
