# Generated by Django 5.2.6 on 2025-10-23 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Уникальный номер стола (например: A-101)', max_length=10, unique=True, verbose_name='Номер стола')),
                ('location', models.CharField(blank=True, help_text='Описание расположения стола в офисе', max_length=100, verbose_name='Расположение')),
                ('coordinates_x', models.IntegerField(default=0, help_text='Координата X на плане офиса', verbose_name='Координата X')),
                ('coordinates_y', models.IntegerField(default=0, help_text='Координата Y на плане офиса', verbose_name='Координата Y')),
                ('is_available', models.BooleanField(default=True, help_text='Доступен ли стол для бронирования', verbose_name='Доступен')),
            ],
            options={
                'verbose_name': 'Рабочий стол',
                'verbose_name_plural': 'Рабочие столы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название профессионального навыка', max_length=100, verbose_name='Название навыка')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Имя сотрудника', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Фамилия сотрудника', max_length=100, verbose_name='Фамилия')),
                ('position', models.CharField(choices=[('backend', 'Бекенд-разработчик'), ('frontend', 'Фронтенд-разработчик'), ('tester', 'Тестировщик'), ('manager', 'Менеджер'), ('designer', 'Дизайнер'), ('devops', 'DevOps инженер'), ('analyst', 'Аналитик')], default='backend', help_text='Должность сотрудника в компании', max_length=20, verbose_name='Должность')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, help_text='Дата начала работы в компании', verbose_name='Дата приёма на работу')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', help_text='Пол сотрудника', max_length=10, verbose_name='Пол')),
                ('email', models.EmailField(blank=True, help_text='Корпоративный email адрес', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Контактный телефон', max_length=20, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, help_text='Работает ли сотрудник в компании', verbose_name='Активен')),
                ('desk', models.ForeignKey(blank=True, help_text='Закрепленный рабочий стол', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.desk', verbose_name='Рабочий стол')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Фотография сотрудника', upload_to='employees/gallery/%Y/%m/%d/', verbose_name='Изображение')),
                ('description', models.CharField(blank=True, help_text='Описание изображения', max_length=200, verbose_name='Описание')),
                ('is_main', models.BooleanField(default=False, help_text='Использовать как основное фото', verbose_name='Основное фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='employee.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Изображение сотрудника',
                'verbose_name_plural': 'Изображения сотрудников',
                'ordering': ['-is_main', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Начальный'), (2, 'Средний'), (3, 'Продвинутый'), (4, 'Эксперт')], help_text='Уровень владения навыком', verbose_name='Уровень освоения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='employee.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Навык сотрудника',
                'verbose_name_plural': 'Навыки сотрудников',
                'ordering': ['-level', 'skill__name'],
                'unique_together': {('employee', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(help_text='Профессиональные навыки сотрудника', through='employee.EmployeeSkill', to='employee.skill', verbose_name='Навыки'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата бронирования')),
                ('start_time', models.TimeField(default='09:00', verbose_name='Время начала')),
                ('end_time', models.TimeField(default='18:00', verbose_name='Время окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.desk', verbose_name='Стол')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-date', 'desk__number'],
                'unique_together': {('desk', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='employee_em_last_na_9f0101_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['position'], name='employee_em_positio_e45583_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['hire_date'], name='employee_em_hire_da_332649_idx'),
        ),
    ]
