# Generated by Django 5.2.7 on 2025-10-16 06:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('position', models.CharField(choices=[('backend', 'Бекенд-разработчик'), ('frontend', 'Фронтенд-разработчик'), ('tester', 'Тестировщик'), ('manager', 'Менеджер'), ('designer', 'Дизайнер')], max_length=20, verbose_name='Должность')),
                ('desk_number', models.IntegerField(blank=True, null=True, verbose_name='Номер стола')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата приёма на работу')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название навыка')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='employees/', verbose_name='Изображение')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='employee.employee')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Начальный'), (2, 'Средний'), (3, 'Продвинутый'), (4, 'Эксперт')], verbose_name='Уровень освоения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.skill')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(through='employee.EmployeeSkill', to='employee.skill', verbose_name='Навыки'),
        ),
    ]
