# Generated by Django 5.2.7 on 2025-10-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_desk_alter_employee_desk_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='coordinates_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='desk',
            name='coordinates_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='desk',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
