# Generated by Django 5.2.7 on 2025-10-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_desk_coordinates_x_alter_desk_coordinates_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('backend', 'Бекенд-разработчик'), ('frontend', 'Фронтенд-разработчик'), ('tester', 'Тестировщик'), ('manager', 'Менеджер'), ('designer', 'Дизайнер')], default='backend', max_length=20, verbose_name='Должность'),
        ),
    ]
