# Generated by Django 5.2.6 on 2025-10-23 16:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desk',
            options={'ordering': ['number'], 'verbose_name': 'Рабочий стол', 'verbose_name_plural': 'Рабочие столы'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='employeeimage',
            options={'ordering': ['-is_main', 'uploaded_at'], 'verbose_name': 'Изображение сотрудника', 'verbose_name_plural': 'Изображения сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='employeeskill',
            options={'ordering': ['-level', 'skill__name'], 'verbose_name': 'Навык сотрудника', 'verbose_name_plural': 'Навыки сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date', 'desk__number'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='desk_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='desk',
            field=models.ForeignKey(blank=True, help_text='Закрепленный рабочий стол', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.desk', verbose_name='Рабочий стол'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, help_text='Корпоративный email адрес', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Работает ли сотрудник в компании', verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='Контактный телефон', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='employeeimage',
            name='description',
            field=models.CharField(blank=True, help_text='Описание изображения', max_length=200, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='employeeimage',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Использовать как основное фото', verbose_name='Основное фото'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default='18:00', verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default='09:00', verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='desk',
            name='coordinates_x',
            field=models.IntegerField(default=0, help_text='Координата X на плане офиса', verbose_name='Координата X'),
        ),
        migrations.AlterField(
            model_name='desk',
            name='coordinates_y',
            field=models.IntegerField(default=0, help_text='Координата Y на плане офиса', verbose_name='Координата Y'),
        ),
        migrations.AlterField(
            model_name='desk',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Доступен ли стол для бронирования', verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='desk',
            name='location',
            field=models.CharField(blank=True, help_text='Описание расположения стола в офисе', max_length=100, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='desk',
            name='number',
            field=models.CharField(help_text='Уникальный номер стола (например: A-101)', max_length=10, unique=True, verbose_name='Номер стола'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(help_text='Имя сотрудника', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', help_text='Пол сотрудника', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата начала работы в компании', verbose_name='Дата приёма на работу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(help_text='Фамилия сотрудника', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('backend', 'Бекенд-разработчик'), ('frontend', 'Фронтенд-разработчик'), ('tester', 'Тестировщик'), ('manager', 'Менеджер'), ('designer', 'Дизайнер'), ('devops', 'DevOps инженер'), ('analyst', 'Аналитик')], default='backend', help_text='Должность сотрудника в компании', max_length=20, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(help_text='Профессиональные навыки сотрудника', through='employee.EmployeeSkill', to='employee.skill', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='employeeimage',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='employee.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='employeeimage',
            name='image',
            field=models.ImageField(help_text='Фотография сотрудника', upload_to='employees/gallery/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='employeeimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='level',
            field=models.IntegerField(choices=[(1, 'Начальный'), (2, 'Средний'), (3, 'Продвинутый'), (4, 'Эксперт')], help_text='Уровень владения навыком', verbose_name='Уровень освоения'),
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.skill', verbose_name='Навык'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='desk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.desk', verbose_name='Стол'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Название профессионального навыка', max_length=100, verbose_name='Название навыка'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeskill',
            unique_together={('employee', 'skill')},
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='employee_em_last_na_9f0101_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['position'], name='employee_em_positio_e45583_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['hire_date'], name='employee_em_hire_da_332649_idx'),
        ),
    ]
